apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec: 
  selector:
    matchLabels: 
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: florinpana01/tradetreasure-gateway-repository
          ports:
            - containerPort: 8003
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gateway-db-secret
                  key: timelinename
            - name: DB_PASS
              valueFrom: 
                secretKeyRef:
                  name: gateway-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gateway-db-secret
                  key: database
